// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC352_g2mBVY2_Wq69Fb69PMrwPVGwwmGk',
    appId: '1:390902626881:web:400305e03547a07d8764c0',
    messagingSenderId: '390902626881',
    projectId: 'inti-enrolment-system',
    authDomain: 'inti-enrolment-system.firebaseapp.com',
    storageBucket: 'inti-enrolment-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5A3NdSfTBRX25UnxWoBV88cZnmMn5cqg',
    appId: '1:390902626881:android:f8a14a96a24be7a68764c0',
    messagingSenderId: '390902626881',
    projectId: 'inti-enrolment-system',
    storageBucket: 'inti-enrolment-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABrxLFPaZjyvCD_Adku5L9j-3n0wEdTpg',
    appId: '1:390902626881:ios:830468472fa7fbb08764c0',
    messagingSenderId: '390902626881',
    projectId: 'inti-enrolment-system',
    storageBucket: 'inti-enrolment-system.firebasestorage.app',
    iosBundleId: 'com.example.inti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABrxLFPaZjyvCD_Adku5L9j-3n0wEdTpg',
    appId: '1:390902626881:ios:830468472fa7fbb08764c0',
    messagingSenderId: '390902626881',
    projectId: 'inti-enrolment-system',
    storageBucket: 'inti-enrolment-system.firebasestorage.app',
    iosBundleId: 'com.example.inti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC352_g2mBVY2_Wq69Fb69PMrwPVGwwmGk',
    appId: '1:390902626881:web:77084745864622c58764c0',
    messagingSenderId: '390902626881',
    projectId: 'inti-enrolment-system',
    authDomain: 'inti-enrolment-system.firebaseapp.com',
    storageBucket: 'inti-enrolment-system.firebasestorage.app',
  );
}
